# Generated by Django 3.2.9 on 2022-07-26 22:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todoitem',
            options={'ordering': ['fecha_caducidad']},
        ),
        migrations.RenameField(
            model_name='todoitem',
            old_name='fecha_completado',
            new_name='fecha_caducidad',
        ),
    ]
